apiVersion: v1
kind: Service
metadata:
  name: complete-production-pipeline
  labels:
    run: complete-production-pipeline
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: complete-production-pipeline
